steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['rm', '-rf', '*', '.*']
    id: 'Clean Directory'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['init']
    id: 'Git: init repo'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['remote', 'add', 'origin', '$_GITHUB_REPO_ADDRESS']
    id: 'Git: Add Origin'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['fetch']
    id: 'Git: Fetch'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['reset', '--hard']
    id: 'Git: Reset'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['checkout', 'origin/$BRANCH_NAME']
    id: 'Git: Checkout'
  - name: 'gcr.io/$PROJECT_ID/git-lfs'
    args: ['lfs', 'pull']
    id: 'LFS: Pull'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - api
      - '-f'
      - api/Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=5b3c076a-6cd3-4852-81c9-f6d4bd52defa
  _TRIGGER_ID: 5b3c076a-6cd3-4852-81c9-f6d4bd52defa
  _SERVICE_NAME: a-real-news-site
  _DEPLOY_REGION: us-east1
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _GITHUB_REPO_ADDRESS: git@github.com:EranSch/ht-titles.git
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - a-real-news-site